
pipeline:

  rsync:
    user: $$PROD_USER
    host: $$PROD_HOST
    port: 22
    source: ./docker-compose.yml
    target: /tmp/$$COMMIT/
    delete: false
    commands:
      - docker-compose -f /tmp/$$COMMIT/docker-compose.yml pull
      - docker-compose -f /tmp/$$COMMIT/docker-compose.yml -p russtress-web up -d
    when:
      branch: master

  docker:
    image: plugins/docker
    storage_driver: vfs
    repo: omelhoro1/russtress-api
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  deploy:
    image: drillster/drone-rsync
    user: captain
    hosts: [ "igor-fischer.rocks" ]
    port: 22
    target: /tmp/russtress-web-${DRONE_COMMIT}/
    include:
      - "docker-compose.yml"
    exclude:
      - "**.*"
    delete: false
    secrets: [ rsync_key ]
    script:
      - docker-compose -f /tmp/russtress-web-${DRONE_COMMIT}/docker-compose.yml pull
      - docker-compose -f /tmp/russtress-web-${DRONE_COMMIT}/docker-compose.yml -p russtress-web up -d
    when:
      branch: master
