version: '2'
services:

  russtress-client:
    image: omelhoro1/russtress-client
    container_name: russtress-client
    restart: unless-stopped
    # ports:
    #   - "5000:5000"
    labels:
      - "traefik.frontend.rule=Host:russtress.igor-fischer.rocks,russtress.fischerops.com"
    environment:
      - SET_STRESS_API=http://russtress-api:5001
    networks:
      - proxy-tier

  russtress-api:
    image: omelhoro1/russtress-api
    container_name: russtress-api
    restart: unless-stopped
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
