// Generated by CoffeeScript 1.7.1
(function() {
  var $, set_stress;

  $ = jQuery;

  set_stress = function(t, cl) {
    var RUS_VOWELS, d, itm, split_t, vows, _i, _len;
    split_t = t.split(/([,.;!?() ])/g);
    RUS_VOWELS = /[`иеаоуяюыёэ]/gi;
    d = {};
    for (_i = 0, _len = split_t.length; _i < _len; _i++) {
      itm = split_t[_i];
      vows = itm.match(RUS_VOWELS);
      if (vows !== null && vows.length > 1) {
        d[itm] = "";
      }
    }
    return $.getJSON("/stress", d, function(d) {
      var f_replace, outp, stress, w;
      f_replace = function(nth, i) {
        var f_r;
        if (i == null) {
          i = 0;
        }
        f_r = function(m, j, string) {
          i++;
          if (i === nth) {
            return "'" + m;
          } else {
            return m;
          }
        };
        return f_r;
      };
      stress = function(w) {
        var e, nth;
        try {
          nth = d[w][0];
          return w.replace(RUS_VOWELS, f_replace(nth));
        } catch (_error) {
          e = _error;
          return w;
        }
      };
      outp = (function() {
        var _j, _len1, _results;
        _results = [];
        for (_j = 0, _len1 = split_t.length; _j < _len1; _j++) {
          w = split_t[_j];
          _results.push(stress(w));
        }
        return _results;
      })();
      return cl(outp);
    });
  };

  ($('#go_stress')).click(function(e) {
    var append_text, t;
    t = ($('#stress_text')).val();
    append_text = function(outp) {
      return ($('#output_stress')).val(outp.join(""));
    };
    return set_stress(t, append_text);
  });

}).call(this);
