// Generated by CoffeeScript 1.8.0
(function() {
  var $, set_stress;

  $ = jQuery;

  set_stress = function(t, cl) {
    var RUS_VOWELS, d, itm, split_t, vows, w, _i, _len;
    split_t = (function() {
      var _i, _len, _ref, _results;
      _ref = t.split(/([\u2000-\u206F\u2E00-\u2E7F\'!\"#\$%&\(\)\*\+,\-\.\/:;<=>\?@\[\]\^_`\{\|\}~ \n])/g);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        w = _ref[_i];
        if (w) {
          _results.push(w);
        }
      }
      return _results;
    })();
    RUS_VOWELS = /[`иеаоуяюыёэ]/gi;
    d = {};
    for (_i = 0, _len = split_t.length; _i < _len; _i++) {
      itm = split_t[_i];
      vows = itm.match(RUS_VOWELS);
      if (vows !== null && vows.length > 1) {
        d[itm] = "";
      }
    }
    return $.getJSON("/stress", d, function(d) {
      var f_replace, outp, stress;
      f_replace = function(nth, i) {
        var f_r;
        if (i == null) {
          i = 0;
        }
        f_r = function(m, j, string) {
          i++;
          if (i === nth) {
            return "'" + m;
          } else {
            return m;
          }
        };
        return f_r;
      };
      stress = function(w) {
        var count, e, entry, info, nth, r, stressed;
        try {
          entry = d[w];
          nth = entry[0][0];
          info = entry[0][1];
          count = entry.length === 1 ? "one" : "more";
          stressed = w.replace(RUS_VOWELS, f_replace(nth));
          t = "<span class='" + info + " " + count + "'>" + stressed + "</span>";
          r = [stressed, t];
        } catch (_error) {
          e = _error;
          r = [w, w];
        }
        return r;
      };
      outp = (function() {
        var _j, _len1, _results;
        _results = [];
        for (_j = 0, _len1 = split_t.length; _j < _len1; _j++) {
          w = split_t[_j];
          _results.push(stress(w));
        }
        return _results;
      })();
      return cl(outp);
    });
  };

  ($('#go_stress')).click(function(e) {
    var append_text, t;
    t = ($('#stress_text')).val();
    append_text = function(outp) {
      var concat, w, with_info;
      concat = ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = outp.length; _i < _len; _i++) {
          w = outp[_i];
          _results.push(w[0]);
        }
        return _results;
      })()).join("");
      with_info = $("<div>" + ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = outp.length; _i < _len; _i++) {
          w = outp[_i];
          _results.push(w[1]);
        }
        return _results;
      })()).join("") + "</div>");
      ($('#output_stress')).val(concat);
      return ($("#stress-info")).html(with_info);
    };
    return set_stress(t, append_text);
  });

}).call(this);
