// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  ($('#go_stress')).click(function(e) {
    var RUS_VOWELS, d, itm, k, ress, s, t, tok_set, toks, w, _, _i, _len;
    t = ($('#stress_text')).val();
    toks = (function() {
      var _i, _len, _ref, _results;
      _ref = t.split(" ");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        w = _ref[_i];
        if (w) {
          _results.push(w.trim());
        }
      }
      return _results;
    })();
    RUS_VOWELS = /[`иеаоуяюыёэ]/gi;
    ress = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = toks.length; _i < _len; _i++) {
        s = toks[_i];
        if (s) {
          _results.push([s, s.match(RUS_VOWELS)]);
        }
      }
      return _results;
    })();
    d = {};
    for (_i = 0, _len = ress.length; _i < _len; _i++) {
      itm = ress[_i];
      if (itm[1] === null || itm[1].length > 1) {
        d[itm[0]] = "";
      }
    }
    tok_set = (function() {
      var _results;
      _results = [];
      for (k in d) {
        _ = d[k];
        _results.push(k);
      }
      return _results;
    })();
    console.log(tok_set);
    return $.getJSON("/stress", d, function(d) {
      var f_replace, outp, stress;
      f_replace = function(nth) {
        var f_r, i;
        i = 0;
        f_r = function(m, j, string) {
          i++;
          if (i === nth) {
            return "'" + m;
          } else {
            return m;
          }
        };
        return f_r;
      };
      stress = function(w) {
        var nth;
        try {
          nth = d[w][0];
          return w.replace(RUS_VOWELS, f_replace(nth));
        } catch (_error) {
          e = _error;
          return w;
        }
      };
      outp = (function() {
        var _j, _len1, _results;
        _results = [];
        for (_j = 0, _len1 = toks.length; _j < _len1; _j++) {
          w = toks[_j];
          _results.push(stress(w));
        }
        return _results;
      })();
      return ($('#output_stress')).val(outp.join(" "));
    });
  });

}).call(this);
